### ISSUE TITLE
Unity 2022.3

### ISSUE THREAD

**Issue by Gansol** [Delt06/voxel-terrain#2]
This Mesh Collider is attached to GameObject at path 'Chunk Pool/Pooled Chunk(Clone)/Main Mesh' with Mesh 'Terrain' in Scene 'SampleScene', but the mesh doesn't have any vertices.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Chunks.MeshGeneration.ChunkMeshGenerator:Awake () (at Assets/Scripts/Chunks/MeshGeneration/ChunkMeshGenerator.cs:159)
Pooling.GameObjectPool:Initialize (UnityEngine.GameObject,UnityEngine.Vector3) (at Assets/Scripts/Pooling/GameObjectPool.cs:16)
Pooling.PoolBase`1<UnityEngine.GameObject>:GetObject (UnityEngine.Vector3) (at Assets/Scripts/Pooling/PoolBase.cs:14)
Chunks.World:SpawnNearChunks (Unity.Mathematics.int2,bool) (at Assets/Scripts/Chunks/World.cs:90)
Chunks.World:UpdateChunks (bool) (at Assets/Scripts/Chunks/World.cs:71)
Chunks.World:Start () (at Assets/Scripts/Chunks/World.cs:153)

**Comment by Delt06** [comment]
I no longer maintain the project so you might have to try and fix this on your own by forking the repo.
